<?php /** @var \Hiberus\Test\Block\LastProducts\ProductList $block */ ?>

<ul>
<?php foreach ($block->getLastProducts(10) as $productName): ?>
    <li>
        <span><?= $escaper->escapeHtml($productName) ?></span>
        <a href="<?= $escaper->escapeUrl($block->getUrl('catalogsearch/result', ['q' => $productName ])) ?>">
            <?= __('Search') ?>
        </a>
    </li>
<?php endforeach; ?>
</ul>